--------------------------------------------------------
--  DDL for Trigger AP_HISTORIA2_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AP_HISTORIA2_TRG" 
BEFORE INSERT ON "AP_HISTORIA" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT AP_HISTORIA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "AP_HISTORIA2_TRG" ENABLE;
