--------------------------------------------------------
--  DDL for Trigger KOLUMNY_AUDYTOWE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "KOLUMNY_AUDYTOWE_TRG" 
BEFORE INSERT ON AP_HIST_KOLUMNY_AUDYTOWE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_AP_HIST_KOLUMNY_AUDYTOWE IS NULL THEN
      SELECT AP_KOLUMNY_AUDYTOWE_SEQ.NEXTVAL INTO :NEW.ID_AP_HIST_KOLUMNY_AUDYTOWE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "KOLUMNY_AUDYTOWE_TRG" ENABLE;
