--------------------------------------------------------
--  DDL for Table AP_HISTORIA
--------------------------------------------------------

  CREATE TABLE "AP_HISTORIA" 
   (	"ID" NUMBER, 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"COLUMN_NAME" VARCHAR2(128 BYTE), 
	"ACTION" VARCHAR2(1 BYTE), 
	"ACTION_DATE" DATE, 
	"ACTION_BY" VARCHAR2(255 BYTE), 
	"DATA_TYPE" VARCHAR2(255 BYTE), 
	"PK1" NUMBER, 
	"TAB_ROW_VERSION" VARCHAR2(200 BYTE), 
	"OLD_VC" VARCHAR2(4000 BYTE), 
	"NEW_VC" VARCHAR2(4000 BYTE), 
	"OLD_NUMBER" NUMBER, 
	"NEW_NUMBER" NUMBER, 
	"OLD_DATE" DATE, 
	"NEW_DATE" DATE, 
	"OLD_TS" TIMESTAMP (6), 
	"NEW_TS" TIMESTAMP (6), 
	"OLD_TSWTZ" TIMESTAMP (6) WITH TIME ZONE, 
	"NEW_TSWTZ" TIMESTAMP (6) WITH TIME ZONE, 
	"OLD_TSWLTZ" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"NEW_TSWLTZ" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"OLD_CLOB" CLOB, 
	"NEW_CLOB" CLOB, 
	"OLD_BLOB" BLOB, 
	"NEW_BLOB" BLOB
   ) ;
